name: uber_direct_api
description: A client library for the Uber Direct API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  retrofit_generator: ^7.0.8
  test: ^1.19.2
  very_good_analysis: ^5.0.0
dependencies:
  dio: ^5.3.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
